package v3.res.soap.webservice.alarmtilt.com;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.1
 * 2015-08-04T19:26:49.082+02:00
 * Generated source version: 3.1.1
 * 
 */
@WebService(targetNamespace = "com.alarmtilt.webservice.soap.res.v3", name = "AlarmTILTRestrictedWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface AlarmTILTRestrictedWebService {

    @WebMethod
    @RequestWrapper(localName = "sendNotification", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "v3.res.soap.webservice.alarmtilt.com.SendNotification")
    @ResponseWrapper(localName = "sendNotificationResponse", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "v3.res.soap.webservice.alarmtilt.com.SendNotificationResponse")
    @WebResult(name = "sendNotificationResult", targetNamespace = "")
    public v3.res.soap.webservice.alarmtilt.com.SendNotificationResult sendNotification(
        @WebParam(name = "authParam", targetNamespace = "")
        v3.res.soap.webservice.alarmtilt.com.AuthParam authParam,
        @WebParam(name = "sendNotificationParam", targetNamespace = "")
        v3.res.soap.webservice.alarmtilt.com.SendNotificationParam sendNotificationParam
    );

    @WebMethod
    @RequestWrapper(localName = "requestSubscription", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "v3.res.soap.webservice.alarmtilt.com.RequestSubscription")
    @ResponseWrapper(localName = "requestSubscriptionResponse", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "v3.res.soap.webservice.alarmtilt.com.RequestSubscriptionResponse")
    @WebResult(name = "requestSubscriptionResult", targetNamespace = "")
    public v3.res.soap.webservice.alarmtilt.com.RequestSubscriptionResult requestSubscription(
        @WebParam(name = "authParam", targetNamespace = "")
        v3.res.soap.webservice.alarmtilt.com.AuthParam authParam,
        @WebParam(name = "requestSubscriptionParam", targetNamespace = "")
        v3.res.soap.webservice.alarmtilt.com.RequestSubscriptionParam requestSubscriptionParam
    );

    @WebMethod
    @RequestWrapper(localName = "pingService", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "v3.res.soap.webservice.alarmtilt.com.PingService")
    @ResponseWrapper(localName = "pingServiceResponse", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "v3.res.soap.webservice.alarmtilt.com.PingServiceResponse")
    @WebResult(name = "pingServiceResult", targetNamespace = "")
    public v3.res.soap.webservice.alarmtilt.com.PingServiceResult pingService();

    @WebMethod
    @RequestWrapper(localName = "importAgenda", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "v3.res.soap.webservice.alarmtilt.com.ImportAgenda")
    @ResponseWrapper(localName = "importAgendaResponse", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "v3.res.soap.webservice.alarmtilt.com.ImportAgendaResponse")
    @WebResult(name = "importAgendaResult", targetNamespace = "")
    public v3.res.soap.webservice.alarmtilt.com.ImportAgendaResult importAgenda(
        @WebParam(name = "authParam", targetNamespace = "")
        v3.res.soap.webservice.alarmtilt.com.AuthParam authParam,
        @WebParam(name = "importAgendaParam", targetNamespace = "")
        v3.res.soap.webservice.alarmtilt.com.ImportAgendaParam importAgendaParam
    );

    @WebMethod
    @RequestWrapper(localName = "validateSubscription", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "v3.res.soap.webservice.alarmtilt.com.ValidateSubscription")
    @ResponseWrapper(localName = "validateSubscriptionResponse", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "v3.res.soap.webservice.alarmtilt.com.ValidateSubscriptionResponse")
    @WebResult(name = "validateSubscriptionResult", targetNamespace = "")
    public v3.res.soap.webservice.alarmtilt.com.ValidateSubscriptionResult validateSubscription(
        @WebParam(name = "authParam", targetNamespace = "")
        v3.res.soap.webservice.alarmtilt.com.AuthParam authParam,
        @WebParam(name = "validationSubscriptionParam", targetNamespace = "")
        v3.res.soap.webservice.alarmtilt.com.ValidateSubscriptionParam validationSubscriptionParam
    );

    @WebMethod
    @RequestWrapper(localName = "getContactUser", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "v3.res.soap.webservice.alarmtilt.com.GetContactUser")
    @ResponseWrapper(localName = "getContactUserResponse", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "v3.res.soap.webservice.alarmtilt.com.GetContactUserResponse")
    @WebResult(name = "getContactUserResult", targetNamespace = "")
    public v3.res.soap.webservice.alarmtilt.com.GetContactUserResult getContactUser(
        @WebParam(name = "authParam", targetNamespace = "")
        v3.res.soap.webservice.alarmtilt.com.AuthParam authParam,
        @WebParam(name = "getContactUserParam", targetNamespace = "")
        v3.res.soap.webservice.alarmtilt.com.GetContactUserParam getContactUserParam
    );

    @WebMethod
    @RequestWrapper(localName = "launchProcedure", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "v3.res.soap.webservice.alarmtilt.com.LaunchProcedure")
    @ResponseWrapper(localName = "launchProcedureResponse", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "v3.res.soap.webservice.alarmtilt.com.LaunchProcedureResponse")
    @WebResult(name = "launchProcedureResult", targetNamespace = "")
    public v3.res.soap.webservice.alarmtilt.com.LaunchProcedureResult launchProcedure(
        @WebParam(name = "authParam", targetNamespace = "")
        v3.res.soap.webservice.alarmtilt.com.AuthParam authParam,
        @WebParam(name = "launchProcedureParam", targetNamespace = "")
        v3.res.soap.webservice.alarmtilt.com.LaunchProcedureParam launchProcedureParam
    );

    @WebMethod
    @RequestWrapper(localName = "listContact", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "v3.res.soap.webservice.alarmtilt.com.ListContact")
    @ResponseWrapper(localName = "listContactResponse", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "v3.res.soap.webservice.alarmtilt.com.ListContactResponse")
    @WebResult(name = "listContactResult", targetNamespace = "")
    public v3.res.soap.webservice.alarmtilt.com.ListContactResult listContact(
        @WebParam(name = "authParam", targetNamespace = "")
        v3.res.soap.webservice.alarmtilt.com.AuthParam authParam,
        @WebParam(name = "listContactParam", targetNamespace = "")
        v3.res.soap.webservice.alarmtilt.com.ListContactParam listContactParam
    );

    @WebMethod
    @RequestWrapper(localName = "listSubscription", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "v3.res.soap.webservice.alarmtilt.com.ListSubscription")
    @ResponseWrapper(localName = "listSubscriptionResponse", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "v3.res.soap.webservice.alarmtilt.com.ListSubscriptionResponse")
    @WebResult(name = "listSubscriptionResult", targetNamespace = "")
    public v3.res.soap.webservice.alarmtilt.com.ListSubscriptionResult listSubscription(
        @WebParam(name = "authParam", targetNamespace = "")
        v3.res.soap.webservice.alarmtilt.com.AuthParam authParam,
        @WebParam(name = "listSubscriptionParam", targetNamespace = "")
        v3.res.soap.webservice.alarmtilt.com.ListSubscriptionParam listSubscriptionParam
    );

    @WebMethod
    @RequestWrapper(localName = "listContactUser", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "v3.res.soap.webservice.alarmtilt.com.ListContactUser")
    @ResponseWrapper(localName = "listContactUserResponse", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "v3.res.soap.webservice.alarmtilt.com.ListContactUserResponse")
    @WebResult(name = "listContactUserResult", targetNamespace = "")
    public v3.res.soap.webservice.alarmtilt.com.ListContactUserResult listContactUser(
        @WebParam(name = "authParam", targetNamespace = "")
        v3.res.soap.webservice.alarmtilt.com.AuthParam authParam,
        @WebParam(name = "listContactUserParam", targetNamespace = "")
        v3.res.soap.webservice.alarmtilt.com.ListContactUserParam listContactUserParam
    );

    @WebMethod
    @RequestWrapper(localName = "exportAgenda", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "v3.res.soap.webservice.alarmtilt.com.ExportAgenda")
    @ResponseWrapper(localName = "exportAgendaResponse", targetNamespace = "com.alarmtilt.webservice.soap.res.v3", className = "v3.res.soap.webservice.alarmtilt.com.ExportAgendaResponse")
    @WebResult(name = "exportAgendaResult", targetNamespace = "")
    public v3.res.soap.webservice.alarmtilt.com.ExportAgendaResult exportAgenda(
        @WebParam(name = "authParam", targetNamespace = "")
        v3.res.soap.webservice.alarmtilt.com.AuthParam authParam,
        @WebParam(name = "exportAgendaParam", targetNamespace = "")
        v3.res.soap.webservice.alarmtilt.com.ExportAgendaParam exportAgendaParam
    );
}
