package v3.res.soap.webservice.alarmtilt.com;

public final class AlarmTILTRestrictedWebService_AlarmTILTRestrictedWebServicePort_Client {

	// NOP
	
}

/**
 * Please modify this class to meet your needs
 * This class is not complete
 * This class was generated by Apache CXF 3.1.1
 * 2015-08-04T19:26:48.971+02:00
 * Generated source version: 3.1.1
 *

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

 
public final class AlarmTILTRestrictedWebService_AlarmTILTRestrictedWebServicePort_Client {

    private static final QName SERVICE_NAME = new QName("com.alarmtilt.webservice.soap.res.v3", "ws-res-v3");

    private AlarmTILTRestrictedWebService_AlarmTILTRestrictedWebServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WsResV3.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WsResV3 ss = new WsResV3(wsdlURL, SERVICE_NAME);
        AlarmTILTRestrictedWebService port = ss.getAlarmTILTRestrictedWebServicePort();  
        
        {
        System.out.println("Invoking sendNotification...");
        v3.res.soap.webservice.alarmtilt.com.AuthParam _sendNotification_authParam = null;
        v3.res.soap.webservice.alarmtilt.com.SendNotificationParam _sendNotification_sendNotificationParam = null;
        v3.res.soap.webservice.alarmtilt.com.SendNotificationResult _sendNotification__return = port.sendNotification(_sendNotification_authParam, _sendNotification_sendNotificationParam);
        System.out.println("sendNotification.result=" + _sendNotification__return);


        }
        {
        System.out.println("Invoking requestSubscription...");
        v3.res.soap.webservice.alarmtilt.com.AuthParam _requestSubscription_authParam = null;
        v3.res.soap.webservice.alarmtilt.com.RequestSubscriptionParam _requestSubscription_requestSubscriptionParam = null;
        v3.res.soap.webservice.alarmtilt.com.RequestSubscriptionResult _requestSubscription__return = port.requestSubscription(_requestSubscription_authParam, _requestSubscription_requestSubscriptionParam);
        System.out.println("requestSubscription.result=" + _requestSubscription__return);


        }
        {
        System.out.println("Invoking pingService...");
        v3.res.soap.webservice.alarmtilt.com.PingServiceResult _pingService__return = port.pingService();
        System.out.println("pingService.result=" + _pingService__return);


        }
        {
        System.out.println("Invoking importAgenda...");
        v3.res.soap.webservice.alarmtilt.com.AuthParam _importAgenda_authParam = null;
        v3.res.soap.webservice.alarmtilt.com.ImportAgendaParam _importAgenda_importAgendaParam = null;
        v3.res.soap.webservice.alarmtilt.com.ImportAgendaResult _importAgenda__return = port.importAgenda(_importAgenda_authParam, _importAgenda_importAgendaParam);
        System.out.println("importAgenda.result=" + _importAgenda__return);


        }
        {
        System.out.println("Invoking validateSubscription...");
        v3.res.soap.webservice.alarmtilt.com.AuthParam _validateSubscription_authParam = null;
        v3.res.soap.webservice.alarmtilt.com.ValidateSubscriptionParam _validateSubscription_validationSubscriptionParam = null;
        v3.res.soap.webservice.alarmtilt.com.ValidateSubscriptionResult _validateSubscription__return = port.validateSubscription(_validateSubscription_authParam, _validateSubscription_validationSubscriptionParam);
        System.out.println("validateSubscription.result=" + _validateSubscription__return);


        }
        {
        System.out.println("Invoking getContactUser...");
        v3.res.soap.webservice.alarmtilt.com.AuthParam _getContactUser_authParam = null;
        v3.res.soap.webservice.alarmtilt.com.GetContactUserParam _getContactUser_getContactUserParam = null;
        v3.res.soap.webservice.alarmtilt.com.GetContactUserResult _getContactUser__return = port.getContactUser(_getContactUser_authParam, _getContactUser_getContactUserParam);
        System.out.println("getContactUser.result=" + _getContactUser__return);


        }
        {
        System.out.println("Invoking launchProcedure...");
        v3.res.soap.webservice.alarmtilt.com.AuthParam _launchProcedure_authParam = null;
        v3.res.soap.webservice.alarmtilt.com.LaunchProcedureParam _launchProcedure_launchProcedureParam = null;
        v3.res.soap.webservice.alarmtilt.com.LaunchProcedureResult _launchProcedure__return = port.launchProcedure(_launchProcedure_authParam, _launchProcedure_launchProcedureParam);
        System.out.println("launchProcedure.result=" + _launchProcedure__return);


        }
        {
        System.out.println("Invoking listContact...");
        v3.res.soap.webservice.alarmtilt.com.AuthParam _listContact_authParam = null;
        v3.res.soap.webservice.alarmtilt.com.ListContactParam _listContact_listContactParam = null;
        v3.res.soap.webservice.alarmtilt.com.ListContactResult _listContact__return = port.listContact(_listContact_authParam, _listContact_listContactParam);
        System.out.println("listContact.result=" + _listContact__return);


        }
        {
        System.out.println("Invoking listSubscription...");
        v3.res.soap.webservice.alarmtilt.com.AuthParam _listSubscription_authParam = null;
        v3.res.soap.webservice.alarmtilt.com.ListSubscriptionParam _listSubscription_listSubscriptionParam = null;
        v3.res.soap.webservice.alarmtilt.com.ListSubscriptionResult _listSubscription__return = port.listSubscription(_listSubscription_authParam, _listSubscription_listSubscriptionParam);
        System.out.println("listSubscription.result=" + _listSubscription__return);


        }
        {
        System.out.println("Invoking listContactUser...");
        v3.res.soap.webservice.alarmtilt.com.AuthParam _listContactUser_authParam = null;
        v3.res.soap.webservice.alarmtilt.com.ListContactUserParam _listContactUser_listContactUserParam = null;
        v3.res.soap.webservice.alarmtilt.com.ListContactUserResult _listContactUser__return = port.listContactUser(_listContactUser_authParam, _listContactUser_listContactUserParam);
        System.out.println("listContactUser.result=" + _listContactUser__return);


        }
        {
        System.out.println("Invoking exportAgenda...");
        v3.res.soap.webservice.alarmtilt.com.AuthParam _exportAgenda_authParam = null;
        v3.res.soap.webservice.alarmtilt.com.ExportAgendaParam _exportAgenda_exportAgendaParam = null;
        v3.res.soap.webservice.alarmtilt.com.ExportAgendaResult _exportAgenda__return = port.exportAgenda(_exportAgenda_authParam, _exportAgenda_exportAgendaParam);
        System.out.println("exportAgenda.result=" + _exportAgenda__return);


        }

        System.exit(0);
    }

}

*/
